
osx_image: xcode10.2	

language: objective-c

xcode_project: StackViewController.xcodeproj
xcode_scheme: StackViewController
xcode_destination: platform=iOS Simulator,OS=11.0.1,name=iPhone 5s

branches:
  only:
    - master
    - /svc-*/
    

git:
  quiet: true