name: Build and Test

on: [push]

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: XCode select
      run: xcode-select -s /Applications/Xcode_11.app/Contents/Developer
    - name: XCode build
      run: xcodebuild -configuration Debug -sdk iphoneos
